/* Lithuanian translation of trip data — mirrors window.TRIP structure.
 * Proper nouns (place names, addresses, restaurant names) are intentionally kept in Spanish/English.
 * Structural fields (coords, dates, hours, cost, link, rating, reviews) are unchanged. */

window.TRIP_LT = {
  meta: {
    travellers: 3,
    arrival:   { date: '2026-04-28', time: '18:00', location: 'Adolfo Suárez Madrid-Barajas (MAD)' },
    departure: { date: '2026-05-03', time: '17:00', location: 'Adolfo Suárez Madrid-Barajas (MAD)' },
    hotel: {
      name: 'Hotel López de Hoyos',
      address: 'Calle López de Hoyos 143, Chamartín, 28002 Madrid',
      coords: [40.4453, -3.6745],
      breakfastIncluded: true,
    },
    metroToHotel: 'Avenida de América (L4/L6/L7/L9, ~8 min pėsčiomis); Cartagena (L7, ~7 min)',
    pace: 'Intensyvi — 3-4 lankytinos vietos per dieną ir vakaras',
    transport: 'Tik viešasis (Metro, EMT, Cercanías, AVE/Avant)',
    holidays: 'Gegužės 1 d. (Gegužės diena, valstybinė) • Gegužės 2 d. (Madrido bendruomenės diena)',
    weather: '12-22 °C, daugiausia saulėta, kartais nedidelis lietus',
    budgetTotal: '€1 950–€2 100 (be skrydžių ir viešbučio)',
  },

  days: [
    {
      date: '2026-04-28', label: '1 diena', dayName: 'Antradienis',
      title: 'Atvykimas — tik lengvas vakaras',
      tags: [{ text: 'Atvykimas', kind: 'neutral' }],
      slots: [
        { time: '18:00',       activity: 'Nusileidimas Barajase; muitinė', directions: '' },
        { time: '19:00-19:45', activity: 'Metro į viešbutį; registracija, lagaminai', directions: 'Metro L8 → L4 (~30 min)' },
        { time: '20:00-21:30', activity: 'Pasivaikščiojimas Gran Vía ir Puerta del Sol — apšviesti fasadai, vakarinė minia, Edificio Metrópolis', directions: 'Avda. de América → L6 → Nuevos Ministerios → L10 → Plaza de España; ėjimas Gran Vía iki Sol (~25 min)' },
        { time: '21:30-23:00', activity: 'Vakarienė La Castela (tradiciniai Madrido tapasai)', directions: 'Sol → L2 → Príncipe de Vergara, 6 min pėsčiomis' },
        { time: '23:30',       activity: 'Grįžimas į viešbutį', directions: 'Metro L9 → Avda. de América (10 min)' },
      ],
      dailySpend: '~€135',
    },
    {
      date: '2026-04-29', label: '2 diena', dayName: 'Trečiadienis',
      title: 'Senasis Madridas + Karališkieji rūmai',
      tags: [{ text: 'Senasis Madridas', kind: 'neutral' }, { text: 'Karališkieji rūmai', kind: 'accent' }],
      slots: [
        { time: '09:30-10:00', activity: 'Viešbutis → metro į Ópera', directions: 'L4 → Goya → L2 → Ópera (~25 min — venkite 8-9:30 piko)' },
        { time: '10:00-12:30', activity: 'Karališkieji rūmai + Karališkasis arsenalas (€18; ~2,5 val.). Sosto salė, Stradivarius kolekcija, Karališkoji vaistinė. Rezervuokite internetu iš anksto.', directions: '5 min pėsčiomis nuo Ópera' },
        { time: '12:30-13:00', activity: 'Almudena katedra (nemokama; ~25 min)', directions: 'Greta rūmų' },
        { time: '13:00-14:30', activity: 'Pietūs — Mercado de San Miguel (tapasų degustacija) arba netoliese esantis Mesón del Champiñón', directions: '8 min pėsčiomis' },
        { time: '14:30-15:30', activity: 'Plaza Mayor + Puerta del Sol (km nulis, Tio Pepe ženklas, Lokio ir Žemuogmedžio statula)', directions: 'Viskas 10 min pėsčiomis' },
        { time: '15:30-17:30', activity: 'Laisvas laikas, kava, apsipirkimas Calle Mayor ir Calle Arenal', directions: 'Pėsčiomis' },
        { time: '17:30-19:00', activity: 'Templo de Debod saulėlydžio metu (nemokamas Egipto šventyklos — geriausias nemokamas saulėlydžio taškas Madride)', directions: 'Sol → L3 → Plaza de España, 7 min pėsčiomis' },
        { time: '19:30-21:00', activity: 'Stogo baro saulėlydis — Picalagartos Sky Bar (be įėjimo mokesčio)', directions: '10 min pėsčiomis atgal į Gran Vía' },
        { time: '21:30',       activity: 'Vakarienė — La Barraca (legendinė paella nuo 1935 m.)', directions: '5 min pėsčiomis' },
        { time: '23:30',       activity: 'Viešbutis', directions: 'Gran Vía → L5 → Diego de León → L4 → Avda. de América' },
      ],
      dailySpend: '~€229',
    },
    {
      date: '2026-04-30', label: '3 diena', dayName: 'Ketvirtadienis',
      title: 'Meno trikampis + Bernabéu',
      tags: [{ text: 'Muziejai', kind: 'neutral' }, { text: 'Stadionas', kind: 'accent' }],
      slots: [
        { time: '09:45-10:00', activity: 'Viešbutis → Banco de España', directions: 'L4 → Goya → L2 → Banco de España (~25 min)' },
        { time: '10:00-12:30', activity: 'Museo Nacional del Prado (€15; ~2,5 val.). Velázquez Las Meninas, Goya Juodieji paveikslai, El Greco. Atidarytas pir–šeš 10:00-20:00.', directions: '5 min pėsčiomis nuo metro' },
        { time: '12:30-14:00', activity: 'Pasivaikščiojimas Retiro parke — Kristalų rūmai, Rožių sodas, Estanque (valtys ~€8)', directions: 'Tiesiai nuo Prado, 5 min pėsčiomis iki Puerta de Felipe IV' },
        { time: '14:00-15:30', activity: 'Pietūs Casa Mortero (Michelin-Bib; ~€35-40 asmeniui pietums — prabangūs)', directions: '12 min pėsčiomis' },
        { time: '15:30-17:30', activity: 'Museo Reina Sofía (€12; ~2 val.). Picasso Guernica, Dalí, Miró. Uždaryta antradieniais.', directions: 'L2 → Sol → L1 → Atocha (arba 12 min pėsčiomis)' },
        { time: '18:00',       activity: 'Metro į Bernabéu', directions: 'Atocha → L1 → Tribunal → L10 → Santiago Bernabéu (~30 min)' },
        { time: '18:30-20:30', activity: 'Bernabéu stadiono ekskursija (€35 internetu — ĮEINA Real Madrid muziejus, panoraminiai vaizdai, rūbinės). Rezervuokite iš anksto.', directions: '' },
        { time: '21:00',       activity: 'Vakarienė — Casa Benigna (Chamartín paellos institucija; ~€30 asmeniui)', directions: 'L10 → Cuzco; arba 15 min pėsčiomis' },
        { time: '23:30',       activity: 'Viešbutis', directions: '10 min pėsčiomis' },
      ],
      dailySpend: '~€417',
    },
    {
      date: '2026-05-01', label: '4 diena', dayName: 'Penktadienis',
      title: 'Vienos dienos išvyka į Valensją (AVE)',
      tags: [{ text: 'Vienos dienos išvyka', kind: 'accent' }, { text: 'Valstybinė šventė', kind: 'gold' }],
      note: 'Dauguma valstybinių muziejų (Prado, Reina Sofía, Karališkieji rūmai) uždaryta gegužės 1 d. Tolimoji vienos dienos išvyka yra optimalus dienos panaudojimas. AVE važiuoja įprastu tvarkaraščiu — rezervuokite iš anksto.',
      slots: [
        { time: '06:30',       activity: 'Kėlimasis; pirmasis pusryčių sėdėjimas viešbutyje (paprastai nuo 07:00 — patvirtinkite)', directions: '' },
        { time: '07:15',       activity: 'Viešbutis → Madrid Atocha arba Chamartín', directions: 'L4 į Chamartín tiesiai (15 min) — patvirtinkite išvykimo stotį rezervuojant' },
        { time: '~08:00',      activity: 'Sėdimas į AVE/Iryo į Valencia Joaquín Sorolla (1 val. 54 min tiesioginis, 18 reisų per dieną)', directions: 'Bilietai €29-€60 rezervuojant ≥3 sav. iš anksto' },
        { time: '10:00',       activity: 'Atvykimas į Valencia Joaquín Sorolla — nemokamas maršrutinis autobusas į Estación del Norte (~5 min)', directions: '' },
        { time: '10:15-13:00', activity: 'Senamiestis: Plaza de la Virgen, katedra ir Miguelete (Šventasis Gralis; €9), Lonja de la Seda (€2), Mercado Central', directions: 'Pėsčiomis, ~15 min tarp lankytinų vietų' },
        { time: '13:00-14:30', activity: 'Pietūs — paella jos gimtinėje (La Pepica arba Casa Carmela; ~€25-30 asmeniui)', directions: 'Autobusas EMT 32 iki paplūdimio (~25 min) arba likite centre' },
        { time: '14:30-17:30', activity: 'Ciudad de las Artes y las Ciencias — lauko apžvalga + Oceanogràfic (€34,40) arba Hemisfèric IMAX (€8,80)', directions: 'Autobusas 95 iš centro (15 min) arba 25 min pėsčiomis palei Turia' },
        { time: '17:30-18:30', activity: 'Kava Turia soduose arba sustojimas prie modernistinės Estación del Norte stoties', directions: 'Autobusas 35 į Joaquín Sorolla' },
        { time: '~19:00',      activity: 'Sėdamas į grįžtamąjį AVE į Madridą (paskutinis reisas ~21:15 — pasirinkite 19:00-20:00 laiką)', directions: '1 val. 54 min.' },
        { time: '~21:00',      activity: 'Atvykimas į Atocha arba Chamartín', directions: '' },
        { time: '21:30',       activity: 'Vėlyva, lengva vakarienė — Bodega de la Ardosa (1892 m. tapasų smuklė; tortilla ir salmorejo)', directions: 'Metro į Tribunal' },
        { time: '23:30',       activity: 'Viešbutis', directions: 'Metro' },
      ],
      dailySpend: '€480-€600',
    },
    {
      date: '2026-05-02', label: '5 diena', dayName: 'Šeštadienis',
      title: 'Vienos dienos išvyka į Toledo (Avant)',
      tags: [{ text: 'Vienos dienos išvyka', kind: 'accent' }, { text: 'Madrido bendruomenės šventė', kind: 'gold' }],
      note: 'Madridas važiuoja šeštadienio/šventės transporto tvarkaraščiu. Toledo (Kastilija-La Manča) regioninės šventės neveikiamas — visi pagrindiniai paminklai atidaryti įprastai.',
      slots: [
        { time: '09:00',       activity: 'Viešbutis → Atocha Cercanías', directions: 'L4 → Goya → L2 → Sol → L1 → Atocha (~30 min); arba Cercanías C-1/C-2 iš Chamartín (10 min)' },
        { time: '09:50',       activity: 'Avant Madrid → Toledo. Fiksuota €13,90 vienakryptė; 33 min. Rezervuokite iš anksto — šeštadieniais ~10 reisų.', directions: 'Atocha' },
        { time: '10:25',       activity: 'Atvykimas į Toledo. Maršrutinis autobusas arba 20 min. kopimas į kalvą iki Plaza Zocodover.', directions: '' },
        { time: '10:45-12:30', activity: 'Toledo katedra (Catedral Primada) — gotikinis šedevras. €12 su vienuolyno kiemu ir Kapitulos sale.', directions: '1,5 val.' },
        { time: '12:30-13:30', activity: 'Iglesia de Santo Tomé — El Greco „Grafo Orgaso laidotuvės" (€4); Sinagoga del Tránsito / Sefardų muziejus (šeštadieniais nuo 14:00 nemokama)', directions: '' },
        { time: '13:30-15:00', activity: 'Pietūs — Restaurante Adolfo arba vietinė taberna; carcamusas, kurapka, marcipanai (~€25 asmeniui)', directions: 'Senamiestis' },
        { time: '15:00-16:30', activity: 'Toledo Alcázar ir Karo muziejus — €5; uždaryta pirmadieniais', directions: '' },
        { time: '16:30-17:30', activity: 'Pasivaikščiojimas iki Puente de San Martín; upės kirtimas; Mirador del Valle miesto panoramai', directions: '' },
        { time: '17:30-18:30', activity: 'Marcipanai iš Santo Tomé arba Mazapanes Barroso', directions: '' },
        { time: '19:30',       activity: 'Avant grįžimas į Madridą (paskutinis ~21:30)', directions: '33 min.' },
        { time: '20:30',       activity: 'Lengva vakarienė — Casa Dani (Mercado de la Paz, Salamanca) — patvirtinkite darbo laiką; alternatyviai: Taberna La Daniela (cocido madrileño)', directions: 'Metro Goya' },
        { time: '23:00',       activity: 'Viešbutis', directions: '8 min pėsčiomis' },
      ],
      dailySpend: '~€330',
    },
    {
      date: '2026-05-03', label: '6 diena', dayName: 'Sekmadienis',
      title: 'Išvykimas (17:00) — El Rastro rytas',
      tags: [{ text: 'Išvykimas', kind: 'neutral' }],
      slots: [
        { time: '09:00-10:00', activity: 'Pusryčiai viešbutyje; pakavimas ir išregistravimas (palikite lagaminus registratūroje)', directions: '' },
        { time: '10:00-12:30', activity: 'El Rastro sekmadienio turgus — ikoninis Madrido blusinė mugė, Calle Ribera de Curtidores, La Latina', directions: 'L4 → L2 → L1 → La Latina (~30 min)' },
        { time: '12:30-13:30', activity: 'Tapasų pusryčiai La Latina — Taberna Tempranillo arba Casa Lucio vietovė (cañas + tortilla)', directions: '5 min pėsčiomis' },
        { time: '13:30-14:00', activity: 'Trumpas pasivaikščiojimas Lavapiés — gatvės menas, daugkultūris Madridas', directions: '10 min pėsčiomis' },
        { time: '14:00',       activity: 'Grįžimas į viešbutį metro atsiimti bagažo', directions: 'L1 → L2 → L4 → Avda. de América (~30 min)' },
        { time: '14:45',       activity: 'Viešbutis → Oro uostas', directions: 'L4 → Mar de Cristal → L8 → Aeropuerto T1/T2/T3 arba T4 (~35 min)' },
        { time: '15:30',       activity: 'Oro uoste — saugumas 90+ min iki 17:00 išvykimo', directions: '' },
      ],
      dailySpend: '~€90',
    },
  ],

  attractions: [
    {
      id: 'royal-palace',
      name: 'Royal Palace (Palacio Real)',
      category: 'palace', icon: '👑',
      address: 'Calle de Bailén s/n, 28071',
      hours: 'Bal-Rgs: pir-šeš 10:00-19:00, sek 10:00-16:00. Uždaryti gegužės 1 d.',
      cost: '€18 (nemokama pir-ket 18-20 val., ES/Lot. Am. asmens tapatybės dok.)',
      duration: '2-2,5 val.',
      metro: 'Ópera (L2/L5/R)',
      coords: [40.4179, -3.7141],
      blurb: 'Didžiausi karališkieji rūmai Vakarų Europoje pagal plotą. Sosto salė, Karališkasis arsenalas, Stradivarius kolekcija, Karališkoji vaistinė.',
      link: 'https://tickets.patrimonionacional.es/en/tickets/palacio-real-de-madrid',
    },
    {
      id: 'bernabeu',
      name: 'Santiago Bernabéu Stadium',
      category: 'stadium', icon: '⚽',
      address: 'Av. de Concha Espina 1, 28036',
      hours: 'Pir-šeš 9:30-19:00; sek/šventės 10:00-18:30',
      cost: '€35 internetu (muziejus įskaičiuotas)',
      duration: '1,5-2 val.',
      metro: 'Santiago Bernabéu (L10)',
      coords: [40.4530, -3.6883],
      blurb: 'Ekskursijos bilietas apima muziejų, panoraminius vaizdus, rūbines ir atsargininkų suolus. Rezervuokite internetu — tai ir pinigų taupymo galimybė.',
      link: 'https://www.realmadrid.com/en-US/tour-bernabeu/individual',
    },
    {
      id: 'retiro',
      name: 'Retiro Park',
      category: 'park', icon: '🌳',
      address: 'Plaza de la Independencia, 28001',
      hours: 'Kasdien 06:00-24:00 (vasaros grafiku nuo gegužės)',
      cost: 'Nemokama (valtys ~€8 / 45 min)',
      duration: '2-3 val.',
      metro: 'Retiro (L2), Ibiza (L9)',
      coords: [40.4153, -3.6844],
      blurb: 'Karališkasis parkas miesto centre. Kristalų rūmai, Rožių sodas, Estanque irklavimo ežeras.',
    },
    {
      id: 'gran-via',
      name: 'Gran Vía',
      category: 'street', icon: '🛣️',
      address: 'Gran Vía, 28013',
      hours: 'Visada atidarytas',
      cost: 'Nemokama',
      duration: '~1 val. pasivaikščiojimui',
      metro: 'Gran Vía (L1/L5), Callao (L3/L5)',
      coords: [40.4203, -3.7058],
      blurb: 'Madrido didysis bulvaras — Edificio Metrópolis, Telefónica pastatas, teatrai, neonas naktį.',
    },
    {
      id: 'plaza-mayor',
      name: 'Plaza Mayor',
      category: 'plaza', icon: '🏛️',
      address: 'Plaza Mayor, 28012',
      hours: 'Visada atidarytas',
      cost: 'Nemokama',
      duration: '30-45 min',
      metro: 'Sol (L1/L2/L3), Tirso de Molina (L1)',
      coords: [40.4156, -3.7074],
      blurb: 'Ikoninis XVII a. arkadų aikštė. Felipe III statula; kavinių terasos po kolonadomis.',
    },
    {
      id: 'puerta-sol',
      name: 'Puerta del Sol',
      category: 'plaza', icon: '🏛️',
      address: 'Puerta del Sol, 28013',
      hours: 'Visada atidarytas',
      cost: 'Nemokama',
      duration: '20-30 min',
      metro: 'Sol (L1/L2/L3)',
      coords: [40.4168, -3.7038],
      blurb: 'Simbolinis Madrido centras. Km nulio plokštelė, Tio Pepe ženklas, Lokio ir Žemuogmedžio statula.',
    },
    {
      id: 'prado',
      name: 'Museo Nacional del Prado',
      category: 'museum', icon: '🎨',
      address: 'C. de Ruiz de Alarcón 23, 28014',
      hours: 'Pir-šeš 10:00-20:00; sek 10:00-19:00. Uždarytas gegužės 1 d.',
      cost: '€15 (nemokama paskutines 2 val. kasdien)',
      duration: '2,5 val.',
      metro: 'Banco de España (L2), Atocha (L1)',
      coords: [40.4138, -3.6921],
      blurb: 'Ispanijos flagmaninis meno muziejus. Velázquez, Goya, El Greco, Bosch, Tiziano.',
      link: 'https://www.museodelprado.es/en/visit/opening-times-and-prices',
    },
    {
      id: 'reina-sofia',
      name: 'Museo Reina Sofía',
      category: 'museum', icon: '🎨',
      address: 'C. de Sta. Isabel 52, 28012',
      hours: 'Pir, tre-šeš 10:00-21:00; sek 10:00-14:30. Uždarytas ant. ir gegužės 1 d.',
      cost: '€12 (nemokama pir ir tre-šeš 19:00-21:00; sek 12:30-14:30)',
      duration: '2 val.',
      metro: 'Atocha (L1), Estación del Arte (L1)',
      coords: [40.4080, -3.6943],
      blurb: 'Ispanijos nacionalinis modernaus meno muziejus. Picasso Guernica — centrinė ekspozicija; taip pat Dalí, Miró.',
      link: 'https://www.museoreinasofia.es/en/visit/opening-times/',
    },
    {
      id: 'templo-debod',
      name: 'Templo de Debod',
      category: 'temple', icon: '🏺',
      address: 'C. de Ferraz 1, 28008',
      hours: 'Lauke 24/7; viduje ant-sek 10:00-19:00',
      cost: 'Nemokama',
      duration: '45 min - 1 val.',
      metro: 'Plaza de España (L3/L10), Ventura Rodríguez (L3)',
      coords: [40.4239, -3.7174],
      blurb: 'Tikras Egipto šventyklos kompleksas, dovanoti Ispanijai 1968 m. — geriausias nemokamas saulėlydžio apžvalgos taškas Madride.',
    },
    {
      id: 'mercado-san-miguel',
      name: 'Mercado de San Miguel',
      category: 'market', icon: '🛒',
      address: 'Pl. de San Miguel s/n, 28005',
      hours: 'Kasdien 10:00-24:00',
      cost: 'Nemokamas įėjimas; tapasai €3-€8',
      duration: '1-1,5 val.',
      metro: 'Sol (L1/L2/L3), Tirso de Molina (L1)',
      coords: [40.4154, -3.7088],
      blurb: 'Ikoninis stiklo ir geležies maisto turgus šalia Plaza Mayor. Turistinis, bet gražus — eikite ne piko metu (12-13).',
    },
    {
      id: 'rastro',
      name: 'El Rastro Sunday Market',
      category: 'market', icon: '🛒',
      address: 'Calle Ribera de Curtidores, 28005',
      hours: 'Sekmadieniais ir šventėmis 09:00-15:00',
      cost: 'Nemokama',
      duration: '1,5-2 val.',
      metro: 'La Latina (L5), Tirso de Molina (L1)',
      coords: [40.4096, -3.7080],
      blurb: 'Klasikinis Madrido atvirosios erdvės blusinė mugė — antikvariniai daiktai, oda, vintažiniai drabužiai, vinilas.',
    },
    {
      id: 'almudena',
      name: 'Almudena Cathedral',
      category: 'church', icon: '⛪',
      address: 'C. de Bailén 10, 28013',
      hours: 'Kasdien 10:00-20:30',
      cost: 'Nemokama (auka €1); Muziejus + Kupolas €7',
      duration: '30-45 min',
      metro: 'Ópera (L2/L5/R)',
      coords: [40.4157, -3.7142],
      blurb: 'Moderni katedra priešais Karališkuosius rūmus. Kripta ir kupolas pasiekiami atskirai.',
    },
  ],

  rooftops: [
    {
      id: 'picalagartos',
      name: 'Picalagartos Sky Bar',
      category: 'rooftop', icon: '🍸',
      address: 'C. de Alcalá 4, 28014 (NH Collection Madrid Gran Vía, 8-9 aukštas)',
      coords: [40.4187, -3.7000],
      hours: 'Kasdien ~13:00-01:30',
      cost: 'Be įėjimo mokesčio su užsakymu; rekomenduojama rezervacija',
      bestTime: 'Saulėlydis / auksinė valanda',
      blurb: 'Nemokamas įėjimas į stovimą baro zoną; rezervuokite stalą auksinei valandai. Vaizdai į Gran Vía.',
      link: 'https://www.nh-collection.com/hotel/nh-collection-madrid-gran-via',
    },
    {
      id: 'the-hat',
      name: 'The Hat Rooftop',
      category: 'rooftop', icon: '🍸',
      address: 'C. Imperial 9, 28012 (šalia Plaza Mayor)',
      coords: [40.4140, -3.7088],
      hours: 'Kasdien ~13:00-24:00',
      cost: 'Be įėjimo mokesčio, be minimalaus užsakymo',
      bestTime: 'Vėlyva popietė / saulėlydis',
      blurb: 'Atsipalaiduojantis viešbučio stogas be įėjimo mokesčio ir be rezervacijos. Tiesiog ateikite.',
      link: 'https://www.thehatmadrid.com/the-rooftop',
    },
    {
      id: 'ginkgo',
      name: 'Ginkgo Sky Bar',
      category: 'rooftop', icon: '🍸',
      address: 'Pl. de España 5, 28008 (VP Plaza España Design, 12 aukštas)',
      coords: [40.4234, -3.7126],
      hours: 'Kasdien 12:30-01:30',
      cost: '€3 darbo dienomis / €6 savaitgaliais (panaikinamas rezervuojant)',
      bestTime: 'Saulėlydis, Karališkųjų rūmų siluetas',
      blurb: 'Elegantiška dizaino viešbučio terasa su vaizdu į Plaza de España ir Karališkuosius rūmus.',
      link: 'https://www.vphoteles.com/en/madrid/sky-bar',
    },
    {
      id: 'azotea-bellas-artes',
      name: 'Azotea del Círculo de Bellas Artes',
      category: 'rooftop', icon: '🍸',
      address: 'C. de Alcalá 42, 28014',
      coords: [40.4193, -3.6960],
      hours: 'Kasdien 12:00-02:00',
      cost: '€5-€5,50 įėjimas (apima meno centro prieigą)',
      bestTime: 'Atvykite 30 min prieš saulėlydį',
      blurb: 'Klasikinis Madrido saulėlydžio kadras — Metrópolis kupolas, Gran Vía, Cibeles viename rėme.',
      link: 'https://circulobellasartes.com/azotea/',
    },
    {
      id: '360-rooftop',
      name: '360° Rooftop Bar',
      category: 'rooftop', icon: '🍸',
      address: 'Pl. de España 8, 28008 (Riu Plaza España, 27 aukštas)',
      coords: [40.4233, -3.7117],
      hours: 'Kasdien 11:00-24:00',
      cost: '€5 (dieną) / €10 (vakaras ir savaitgaliai), negrąžinama',
      bestTime: 'Saulėlydis / naktis',
      blurb: 'Aukščiausia 360° miesto panorama Madride. Ilgos eilės piko metu — atvykite anksti.',
      link: 'https://www.riu360rooftopbar.com/en/',
    },
  ],

  restaurants: [
    {
      name: 'La Castela',
      address: 'C. del Doctor Castelo 22, 28009 (Retiro)',
      coords: [40.4183, -3.6741],
      cuisine: 'Tradiciniai Madrido tapasai',
      pricePerPerson: '€20-€25',
      rating: 4.5, reviews: '2 500+',
      atmosphere: 'Judrus, daug vietinių, baltos plytelės baras; šiltas',
      bestDish: 'Croquetas de jamón + tortilla de patata',
      assignedDay: '1 dienos vakarienė',
    },
    {
      name: 'La Barraca',
      address: 'C. de la Reina 29, 28004 (Gran Vía)',
      coords: [40.4194, -3.6987],
      cuisine: 'Valencietiška / paella nuo 1935 m.',
      pricePerPerson: '€28-€35',
      rating: 4.4, reviews: '1 200+',
      atmosphere: 'Senovinio valencietiško interjero restoranas, jaukus, neskubus',
      bestDish: 'Paella valenciana (vištiena ir triušis) arba arroz negro',
      assignedDay: '2 dienos vakarienė',
    },
    {
      name: 'Mercado de San Miguel',
      address: 'Pl. de San Miguel s/n, 28005',
      coords: [40.4154, -3.7088],
      cuisine: 'Tapasų degustacija',
      pricePerPerson: '€15-€25',
      rating: 4.3, reviews: '140 000+',
      atmosphere: 'Judrus stiklinis turgus; perpildytas, bet ikoninis — eikite ne piko metu (12-13)',
      bestDish: 'Jamón ibérico kūgiai, austrės, vermutas',
      assignedDay: '2 dienos pietūs',
    },
    {
      name: 'Casa Mortero',
      address: 'C. de Zorrilla 9, 28014 (Las Cortes)',
      coords: [40.4159, -3.6960],
      cuisine: 'Modernus tradicinis ispaniškas (Michelin-Bib)',
      pricePerPerson: '€35-€45',
      rating: 4.7, reviews: '1 700+',
      atmosphere: 'Minimalistinis-industrinis; ramus; vienas geriausių kainos ir kokybės Madride',
      bestDish: 'Torreznos, jautienos skruostai, keptas menkė',
      assignedDay: '3 dienos pietūs (prabangūs)',
    },
    {
      name: 'Casa Benigna',
      address: 'C. Benigno Soto 9, 28002 (Chamartín)',
      coords: [40.4493, -3.6770],
      cuisine: 'Viduržemio jūros / paella',
      pricePerPerson: '€30-€40',
      rating: 4.6, reviews: '1 000+',
      atmosphere: 'Jaukus gyvenamojo kambario jausmas; šefų stalo atmosfera; būtinos rezervacijos',
      bestDish: 'Paella de pluma ibérica',
      assignedDay: '3 dienos vakarienė',
      note: 'Pėsčiomis nuo viešbučio.',
    },
    {
      name: 'Bodega de la Ardosa',
      address: 'C. de Colón 13, 28004 (Malasaña)',
      coords: [40.4244, -3.7027],
      cuisine: 'Klasikinė 1892 m. tapasų smuklė',
      pricePerPerson: '€15-€25',
      rating: 4.5, reviews: '5 500+',
      atmosphere: 'Senų plytelių ir statinių bodega; stovima ir aukšti stalai',
      bestDish: 'Salmorejo, apdovanota tortilla, vermutas iš čiaupo',
      assignedDay: '4 dienos vėlyvoji vakarienė',
    },
    {
      name: 'Casa Dani',
      address: 'C. de Ayala 28, 28001 (Mercado de la Paz, Salamanca)',
      coords: [40.4254, -3.6822],
      cuisine: 'Tradicinis / menú del día',
      pricePerPerson: '€15-€20',
      rating: 4.5, reviews: '3 500+',
      atmosphere: 'Judri turgaus vieta ir valgomasis; Nacionalinis Tortilla Čempionas',
      bestDish: 'Tortilla de patata con cebolla, callos',
      assignedDay: '5 dienos vakarienė',
    },
    {
      name: 'Taberna Tempranillo',
      address: 'C. Cava Baja 38, 28005 (La Latina)',
      coords: [40.4123, -3.7095],
      cuisine: 'Tapasai + ispaniški vynai',
      pricePerPerson: '€20-€28',
      rating: 4.4, reviews: '2 000+',
      atmosphere: 'Atmosferinė Cava Baja smuklė; didžiulis vynų sąrašas',
      bestDish: 'Pulpo a la gallega, sūrių lenta',
      assignedDay: '6 dienos ryto pusryčiai / vėlyvi pietūs',
    },
  ],

  dayTrips: [
    {
      name: 'Toledo',
      status: 'mandatory',
      assignedDay: 'Šeštadienis, gegužės 2 d.',
      coords: [39.8628, -4.0273],
      highlights: [
        'Toledo katedra (Catedral Primada) — gotikinis šedevras',
        'El Greco „Grafo Orgaso laidotuvės" Iglesia de Santo Tomé',
        'Sinagoga del Tránsito / Sefardų muziejus',
        'Toledo Alcázar ir Karo muziejus',
        'Mirador del Valle miesto panoramai; marcipanų degustacija',
      ],
      transport: 'Renfe Avant Madrid Atocha → Toledo. €13,90 vienakryptė; 33 min. ~14 reisų per dieną darbo dienomis, ~10 savaitgaliais.',
      cost: '~€70-€90 asmeniui (traukinys + paminklai + pietūs)',
      duration: 'Rekomenduojama visa diena (8-10 val.)',
      weather: 'Akmeninis grindinys, kalvota, daugiausia lauke — paimkite lengvą lietinį švarką.',
    },
    {
      name: 'Valencia',
      status: 'mandatory',
      assignedDay: 'Penktadienis, gegužės 1 d.',
      coords: [39.4699, -0.3763],
      highlights: [
        'Valensijos katedra ir Miguelete bokštas (Šventasis Gralis)',
        'Mercado Central; Lonja de la Seda (UNESCO šilko birža)',
        'Ciudad de las Artes y las Ciencias (Calatrava architektūra)',
        'Oceanogràfic arba Hemisfèric IMAX',
        'Malvarrosa paplūdimys + paella jos gimtinėje',
      ],
      transport: 'AVE / Iryo / Avlo / Ouigo į Valencia Joaquín Sorolla. 1 val. 54 min. tiesioginis; ~18 traukinių per dieną. Avlo nuo €29.',
      cost: '€115-€180 asmeniui (traukinys + bilietai + pietūs)',
      duration: 'Visa diena (~9 val. vietoje)',
      weather: 'Patikimai šilčiau nei Madride (22-26 °C); puiki atsarginė galimybė lietingam orui.',
      sameDayVerdict: 'Grįžimas tą pačią dieną yra tinkamas pasirinkimas šiai 5 dienų Madrido kelionei.',
    },
    {
      name: 'Segovia',
      status: 'optional-recommend',
      assignedDay: 'Praleisti — pasilikti kitai kelionei',
      coords: [40.9501, -4.1183],
      highlights: ['Romėnų akvedukas', 'Alcázar (Pelenės pilies įkvėpimas)', 'Katedra'],
      transport: 'AVE 27 min iš Chamartín į Segovia-Guiomar; autobusas 11 į senąjį miestą.',
      cost: '~€26 traukinys',
      duration: 'Pusdienis arba visa diena',
      verdict: 'Labai rekomenduojama, jei turėtumėte 6-ą dieną. Galėtų pakeisti Toledo, tačiau Toledo arčiau ir kultūriškai turtingesnis.',
    },
    {
      name: 'El Escorial',
      status: 'optional-skip',
      assignedDay: 'Praleisti',
      coords: [40.5896, -4.1498],
      highlights: ['UNESCO Pilypo II Karališkasis vienuolynas'],
      transport: 'Cercanías C-3 iš Atocha arba Chamartín, ~1 val. Apimama Turisto Paso Zona T.',
      cost: '~€8,40 į abi puses su Zona T pasu',
      duration: 'Pusdienis',
      verdict: 'Netinka tankiam 5 dienų Madrido maršrutui, nebent praleistumėte Karališkuosius rūmus.',
    },
    {
      name: 'Ávila',
      status: 'optional-skip',
      assignedDay: 'Praleisti',
      coords: [40.6566, -4.6815],
      highlights: ['Pasivaikščiojimas prie miesto sienų', 'Katedra'],
      transport: '~1,5 val. kiekviena kryptimi',
      cost: 'Kintama',
      duration: 'Visa diena',
      verdict: 'Graži, tačiau per daug kelionės 5 dienoms. Geriau suderinti su Segovia.',
    },
    {
      name: 'Alcalá de Henares',
      status: 'optional-recommend',
      assignedDay: 'Praleisti šiame intensyviame maršrute',
      coords: [40.4818, -3.3644],
      highlights: ['Cervanteso gimtinė', 'Universiteto miestas'],
      transport: 'Cercanías C-2 / C-7 iš Chamartín ~40 min; apimama Zonos T pasu.',
      cost: '~€7 su Zona T pasu',
      duration: 'Pusdienis',
      verdict: 'Galimas pusdienis, jei Madrido diena atlaisvėja.',
    },
  ],

  practical: [
    {
      title: 'Valstybinės šventės',
      body: [
        '<strong>Penkt. gegužės 1 d.</strong> — Gegužės diena (valstybinė). Karališkieji rūmai, Prado, Reina Sofía, Thyssen <strong>visi uždaryti</strong>. Metro pagal sekmadienio/šventės tvarkaraštį. AVE/Avant tarpmiestiniu įprastu. Daugelis parduotuvių uždarytos. Planas: išvyka į Valensją.',
        '<strong>Šeštadienis gegužės 2 d.</strong> — Madrido bendruomenės diena (regioninė). Dauguma lankytinų vietų atidarytos, tačiau didelė minia (ilgas savaitgalis). Planas: Toledo (už regiono ribų, neveikiamas).',
      ],
    },
    {
      title: 'Transporto patarimai',
      list: [
        'Venkite 08:00-09:30 ir 18:00-20:00 pir-penkt Metro ir Cercanías.',
        '<strong>Tarjeta Multi kortelė</strong> (€2,50, papildoma) reikalinga bet kokiam pasui ar pavieniam bilietui. Turisto pasas yra asmeninis/neperduodamas.',
        'Naktiniai autobusai (<em>Búhos</em>) važiuoja nuo Plaza de Cibeles po Metro uždarymo; apimama Turisto Paso.',
        'AVE / Avlo / Iryo / Ouigo <strong>neapimami</strong> jokiu kelionės pasu — rezervuokite atskirai.',
      ],
    },
    {
      title: '„City Card" analizė (3 asm., 5 dienos)',
      body: [
        '<strong>Zonos A 5 dienų Turisto Kelionių Pasas</strong>: €32,50 × 3 = €97,50. Apima oro uosto priedą. Pigesnis nei mokėjimas pagal kiekvieną kartą (~€42 asm.) ~€30 iš viso.',
        '<strong>Zonos T pasas</strong> (€49 × 3) vertas tik jei pridedamas El Escorial / Aranjuez. <em>Neapima</em> Avant į Toledo arba AVE į Valensją.',
        'Madrido <strong>„City Card"</strong>: nuolaidos skirtos lankytinoms vietoms, kurių nelankysite; taupymas minimalus, palyginti su Zonos A pasu.',
      ],
      recommendation: '✅ Nusipirkite 3 × Zonos A 5-dienų Turisto Kelionių Pasus atvykus oro uoste — €97,50 grupei.',
    },
    {
      title: 'Daiktų sąrašas — vėlyvas balandis / gegužės pradžia',
      body: ['Dienos maks. 18-22 °C, naktinis min. 9-12 °C, ~21 % lietaus tikimybė per dieną, ~10 °C skirtumas dieną-naktį.'],
      list: [
        'Patogūs vaikščiojimo batai (Toledo akmeninis grindinys).',
        'Sluoksniai: marškinėliai + lengvas megztinis + sulankstoma striukė.',
        'Lengva lietinė striukė / kompaktiškas skėtis.',
        'Elegantiškas-kasdieniškas apdaras stogo barų ir vakarienių (be šortų/šlepečių).',
        'Kuprinė, akiniai nuo saulės, SPF 30+, ES maitinimo adapteris (C/F tipas).',
        'Asmens tapatybės kortelė/pasas reikalingas Karališkuosiuose rūmuose, Bernabéu, AVE saugume.',
      ],
    },
    {
      title: 'Išankstinis rezervavimas',
      list: [
        'Karališkieji rūmai, Bernabéu ekskursija, Prado, Reina Sofía — laiko bilietas.',
        'AVE/Iryo į Valensją (rezervuokite 3+ sav. iš anksto dėl &lt;€60 tarifų).',
        'Avant į Toledo (šeštadienio reisai sumažinami iki ~10 per dieną).',
        'Casa Mortero, La Barraca, Casa Benigna — rezervuokite 48 val. iš anksto.',
      ],
    },
    {
      title: 'Pinigai ir kt.',
      list: [
        'Turėkite ~€40 grynųjų kiekvienas — daugelis vietų priima korteles, tačiau mažų tapasų barai ir El Rastro pardavėjai teikia pirmenybę grynaisiais.',
        'Madrido vandentiekio vanduo puikus — papildykite butelį prie parkų šaltinių.',
        'Arbatpinigiai: suapvalinkite sąskaitą arba 5-10 % sėdimoje vakarienėje; tapasų baruose neprivaloma.',
      ],
    },
  ],
};
