/* Trip data — all editable in one place. Extracted from the compass research artifact. */

const TRIP = {
  meta: {
    travellers: 3,
    arrival:   { date: '2026-04-28', time: '18:00', location: 'Adolfo Suárez Madrid-Barajas (MAD)' },
    departure: { date: '2026-05-03', time: '17:00', location: 'Adolfo Suárez Madrid-Barajas (MAD)' },
    hotel: {
      name: 'Hotel López de Hoyos',
      address: 'Calle López de Hoyos 143, Chamartín, 28002 Madrid',
      coords: [40.4453, -3.6745],
      breakfastIncluded: true,
    },
    metroToHotel: 'Avenida de América (L4/L6/L7/L9, ~8 min walk); Cartagena (L7, ~7 min)',
    pace: 'Packed — 3-4 sights/day plus evening',
    transport: 'Public only (Metro, EMT, Cercanías, AVE/Avant)',
    holidays: '1 May (Labour Day, national) • 2 May (Día de la Comunidad de Madrid)',
    weather: '12-22 °C, mostly sunny, occasional light rain',
    budgetTotal: '€1,950-€2,100 (excl. flights & hotel)',
  },

  /* Per-day itinerary slots */
  days: [
    {
      date: '2026-04-28', label: 'Day 1', dayName: 'Tuesday',
      title: 'Arrival — light evening only',
      tags: [{ text: 'Arrival', kind: 'neutral' }],
      slots: [
        { time: '18:00',         activity: 'Land at Barajas; clear customs', directions: '' },
        { time: '19:00-19:45',   activity: 'Metro to hotel; check in, drop bags', directions: 'Metro L8 → L4 (~30 min)' },
        { time: '20:00-21:30',   activity: 'Stroll Gran Vía & Puerta del Sol — illuminated façades, evening crowds, Edificio Metrópolis', directions: 'Avda. de América → L6 → Nuevos Ministerios → L10 → Plaza de España; walk Gran Vía to Sol (~25 min)' },
        { time: '21:30-23:00',   activity: 'Dinner at La Castela (traditional Madrileño tapas)', directions: 'Sol → L2 → Príncipe de Vergara, walk 6 min' },
        { time: '23:30',         activity: 'Return to hotel', directions: 'Metro L9 → Avda. de América (10 min)' },
      ],
      dailySpend: '~€135',
    },
    {
      date: '2026-04-29', label: 'Day 2', dayName: 'Wednesday',
      title: 'Old Madrid + Royal Palace',
      tags: [{ text: 'Old Madrid', kind: 'neutral' }, { text: 'Royal Palace', kind: 'accent' }],
      slots: [
        { time: '09:30-10:00', activity: 'Hotel → metro to Ópera', directions: 'L4 → Goya → L2 → Ópera (~25 min — avoid 8-9:30 rush)' },
        { time: '10:00-12:30', activity: 'Royal Palace + Royal Armoury (€18; ~2.5 h). Throne Room, Stradivarius collection, Royal Pharmacy. Pre-book online.', directions: '5 min walk from Ópera' },
        { time: '12:30-13:00', activity: 'Almudena Cathedral (free; ~25 min)', directions: 'Adjacent to palace' },
        { time: '13:00-14:30', activity: 'Lunch — Mercado de San Miguel (sample tapas) or Mesón del Champiñón nearby', directions: '8 min walk' },
        { time: '14:30-15:30', activity: 'Plaza Mayor + Puerta del Sol (km zero, Tio Pepe sign, Bear & Strawberry Tree statue)', directions: 'All within 10 min walk' },
        { time: '15:30-17:30', activity: 'Free time, coffee, shopping on Calle Mayor & Calle Arenal', directions: 'Walking' },
        { time: '17:30-19:00', activity: 'Templo de Debod at sunset (free Egyptian temple — Madrid’s best free sunset spot)', directions: 'Sol → L3 → Plaza de España, 7 min walk' },
        { time: '19:30-21:00', activity: 'Rooftop sundowner — Picalagartos Sky Bar (no entry fee)', directions: '10 min walk back to Gran Vía' },
        { time: '21:30',       activity: 'Dinner — La Barraca (legendary paella since 1935)', directions: '5 min walk' },
        { time: '23:30',       activity: 'Hotel', directions: 'Gran Vía → L5 → Diego de León → L4 → Avda. de América' },
      ],
      dailySpend: '~€229',
    },
    {
      date: '2026-04-30', label: 'Day 3', dayName: 'Thursday',
      title: 'Art Triangle + Bernabéu',
      tags: [{ text: 'Museums', kind: 'neutral' }, { text: 'Stadium', kind: 'accent' }],
      slots: [
        { time: '09:45-10:00', activity: 'Hotel → Banco de España', directions: 'L4 → Goya → L2 → Banco de España (~25 min)' },
        { time: '10:00-12:30', activity: 'Museo Nacional del Prado (€15; ~2.5 h). Velázquez Las Meninas, Goya Black Paintings, El Greco. Open Mon-Sat 10:00-20:00.', directions: '5 min walk from metro' },
        { time: '12:30-14:00', activity: 'Walk through Retiro Park — Crystal Palace, Rose Garden, Estanque (boat rental ~€8)', directions: 'Direct from Prado, 5 min walk to Puerta de Felipe IV' },
        { time: '14:00-15:30', activity: 'Lunch at Casa Mortero (Michelin-Bib; ~€35-40 pp at lunch — splurge)', directions: '12 min walk' },
        { time: '15:30-17:30', activity: 'Museo Reina Sofía (€12; ~2 h). Picasso Guernica, Dalí, Miró. Closed Tuesdays.', directions: 'L2 → Sol → L1 → Atocha (or 12 min walk)' },
        { time: '18:00',       activity: 'Metro to Bernabéu', directions: 'Atocha → L1 → Tribunal → L10 → Santiago Bernabéu (~30 min)' },
        { time: '18:30-20:30', activity: 'Bernabéu Stadium Tour (€35 online — INCLUDES Real Madrid Museum, panoramic views, dressing rooms). Pre-book.', directions: '' },
        { time: '21:00',       activity: 'Dinner — Casa Benigna (Chamartín paella institution; ~€30 pp)', directions: 'L10 → Cuzco; or 15 min walk' },
        { time: '23:30',       activity: 'Hotel', directions: '10 min walk' },
      ],
      dailySpend: '~€417',
    },
    {
      date: '2026-05-01', label: 'Day 4', dayName: 'Friday',
      title: 'Valencia day trip (AVE)',
      tags: [{ text: 'Day trip', kind: 'accent' }, { text: 'Public holiday', kind: 'gold' }],
      note: 'Most state museums (Prado, Reina Sofía, Royal Palace) closed on 1 May. Long-distance day trip is the optimal use of the day. AVE runs a regular timetable — book in advance.',
      slots: [
        { time: '06:30',       activity: 'Wake; first-sitting hotel breakfast (typically from 07:00 — confirm)', directions: '' },
        { time: '07:15',       activity: 'Hotel → Madrid Atocha or Chamartín', directions: 'L4 to Chamartín direct (15 min) — confirm departure station when booking' },
        { time: '~08:00',      activity: 'Board AVE/Iryo to Valencia Joaquín Sorolla (1h 54 min direct, 18 daily services)', directions: 'Tickets €29-€60 if booked ≥3 weeks ahead' },
        { time: '10:00',       activity: 'Arrive Valencia Joaquín Sorolla — free shuttle bus to Estación del Norte (~5 min)', directions: '' },
        { time: '10:15-13:00', activity: 'Old Town walk: Plaza de la Virgen, Cathedral & Miguelete (Holy Grail; €9), Lonja de la Seda (€2), Mercado Central', directions: 'On foot, ~15 min between sights' },
        { time: '13:00-14:30', activity: 'Lunch — paella in its birthplace (La Pepica or Casa Carmela; ~€25-30 pp)', directions: 'Bus EMT 32 to beach (~25 min) or stay in centre' },
        { time: '14:30-17:30', activity: 'Ciudad de las Artes y las Ciencias — exterior + Oceanogràfic (€34.40) or Hemisfèric IMAX (€8.80)', directions: 'Bus 95 from centre (15 min) or 25 min walk along Turia' },
        { time: '17:30-18:30', activity: 'Coffee on Turia gardens or stop at Estación del Norte modernista station', directions: 'Bus 35 to Joaquín Sorolla' },
        { time: '~19:00',      activity: 'Board return AVE to Madrid (last service ~21:15 — pick the 19:00-20:00 slot)', directions: '1h 54 min' },
        { time: '~21:00',      activity: 'Arrive Atocha or Chamartín', directions: '' },
        { time: '21:30',       activity: 'Late, light dinner — Bodega de la Ardosa (1892 tapas tavern; tortilla & salmorejo)', directions: 'Metro to Tribunal' },
        { time: '23:30',       activity: 'Hotel', directions: 'Metro' },
      ],
      dailySpend: '€480-€600',
    },
    {
      date: '2026-05-02', label: 'Day 5', dayName: 'Saturday',
      title: 'Toledo day trip (Avant)',
      tags: [{ text: 'Day trip', kind: 'accent' }, { text: 'Comunidad de Madrid holiday', kind: 'gold' }],
      note: 'Madrid runs Saturday/holiday transport schedule. Toledo (Castilla-La Mancha) is unaffected by the regional holiday — all major monuments open normally.',
      slots: [
        { time: '09:00',       activity: 'Hotel → Atocha Cercanías', directions: 'L4 → Goya → L2 → Sol → L1 → Atocha (~30 min); or Cercanías C-1/C-2 from Chamartín (10 min)' },
        { time: '09:50',       activity: 'Avant Madrid → Toledo. Fixed €13.90 each way; 33 min. Book in advance — Sat ~10 services.', directions: 'Atocha' },
        { time: '10:25',       activity: 'Arrive Toledo. Shuttle bus or 20-min uphill walk to Plaza Zocodover.', directions: '' },
        { time: '10:45-12:30', activity: 'Toledo Cathedral (Catedral Primada) — Gothic masterpiece. €12 incl. Cloister & Chapter House.', directions: '1.5 h' },
        { time: '12:30-13:30', activity: 'Iglesia de Santo Tomé — El Greco Burial of Count Orgaz (€4); Sinagoga del Tránsito / Sephardic Museum (Sat 14:00 free)', directions: '' },
        { time: '13:30-15:00', activity: 'Lunch — Restaurante Adolfo or local taberna; carcamusas, partridge, marzipan (~€25 pp)', directions: 'Old town' },
        { time: '15:00-16:30', activity: 'Alcázar of Toledo & Army Museum — €5; closed Mondays', directions: '' },
        { time: '16:30-17:30', activity: 'Walk to Puente de San Martín; cross river; Mirador del Valle for skyline panorama', directions: '' },
        { time: '17:30-18:30', activity: 'Marzipan from Santo Tomé or Mazapanes Barroso', directions: '' },
        { time: '19:30',       activity: 'Avant return to Madrid (last ~21:30)', directions: '33 min' },
        { time: '20:30',       activity: 'Light dinner — Casa Dani (Mercado de la Paz, Salamanca) — confirm hours; alt: Taberna La Daniela for cocido madrileño', directions: 'Metro Goya' },
        { time: '23:00',       activity: 'Hotel', directions: '8 min walk' },
      ],
      dailySpend: '~€330',
    },
    {
      date: '2026-05-03', label: 'Day 6', dayName: 'Sunday',
      title: 'Departure (17:00) — El Rastro morning',
      tags: [{ text: 'Departure', kind: 'neutral' }],
      slots: [
        { time: '09:00-10:00', activity: 'Hotel breakfast; pack & check out (leave bags at reception)', directions: '' },
        { time: '10:00-12:30', activity: 'El Rastro Sunday Market — Madrid’s iconic flea market on Calle Ribera de Curtidores, La Latina', directions: 'L4 → L2 → L1 → La Latina (~30 min)' },
        { time: '12:30-13:30', activity: 'Tapas brunch in La Latina — Taberna Tempranillo or Casa Lucio area (cañas + tortilla)', directions: '5 min walk' },
        { time: '13:30-14:00', activity: 'Quick stroll Lavapiés — street art, multicultural Madrid', directions: '10 min walk' },
        { time: '14:00',       activity: 'Return to hotel via metro to collect luggage', directions: 'L1 → L2 → L4 → Avda. de América (~30 min)' },
        { time: '14:45',       activity: 'Hotel → Airport', directions: 'L4 → Mar de Cristal → L8 → Aeropuerto T1/T2/T3 or T4 (~35 min)' },
        { time: '15:30',       activity: 'At airport — security 90+ min before 17:00 departure', directions: '' },
      ],
      dailySpend: '~€90',
    },
  ],

  /* All sights — used in the Sights grid. */
  attractions: [
    {
      id: 'royal-palace',
      name: 'Royal Palace (Palacio Real)',
      category: 'palace', icon: '👑',
      address: 'Calle de Bailén s/n, 28071',
      hours: 'Apr-Sep: Mon-Sat 10:00-19:00, Sun 10:00-16:00. Closed 1 May.',
      cost: '€18 (free Mon-Thu 18-20h, EU/Latin Am ID)',
      duration: '2-2.5 h',
      metro: 'Ópera (L2/L5/R)',
      coords: [40.4179, -3.7141],
      blurb: 'Largest royal palace in Western Europe by floor area. Throne Room, Royal Armoury, Stradivarius collection, Royal Pharmacy.',
      link: 'https://tickets.patrimonionacional.es/en/tickets/palacio-real-de-madrid',
    },
    {
      id: 'bernabeu',
      name: 'Santiago Bernabéu Stadium',
      category: 'stadium', icon: '⚽',
      address: 'Av. de Concha Espina 1, 28036',
      hours: 'Mon-Sat 9:30-19:00; Sun/holidays 10:00-18:30',
      cost: '€35 online (museum included — no separate ticket)',
      duration: '1.5-2 h',
      metro: 'Santiago Bernabéu (L10)',
      coords: [40.4530, -3.6883],
      blurb: 'Tour ticket bundles museum, panoramic views, dressing rooms and dugouts. Pre-book online; this *is* the cost-saving option.',
      link: 'https://www.realmadrid.com/en-US/tour-bernabeu/individual',
    },
    {
      id: 'retiro',
      name: 'Retiro Park',
      category: 'park', icon: '🌳',
      address: 'Plaza de la Independencia, 28001',
      hours: 'Daily 06:00-24:00 (summer hours from May)',
      cost: 'Free (boat rental ~€8 / 45 min)',
      duration: '2-3 h',
      metro: 'Retiro (L2), Ibiza (L9)',
      coords: [40.4153, -3.6844],
      blurb: 'Royal park in the heart of the city. Crystal Palace, Rose Garden, Estanque rowboat lake.',
    },
    {
      id: 'gran-via',
      name: 'Gran Vía',
      category: 'street', icon: '🛣️',
      address: 'Gran Vía, 28013',
      hours: 'Always open',
      cost: 'Free',
      duration: '~1 h walk',
      metro: 'Gran Vía (L1/L5), Callao (L3/L5)',
      coords: [40.4203, -3.7058],
      blurb: 'Madrid’s grand boulevard — Edificio Metrópolis, Telefónica building, theatres, neon by night.',
    },
    {
      id: 'plaza-mayor',
      name: 'Plaza Mayor',
      category: 'plaza', icon: '🏛️',
      address: 'Plaza Mayor, 28012',
      hours: 'Always open',
      cost: 'Free',
      duration: '30-45 min',
      metro: 'Sol (L1/L2/L3), Tirso de Molina (L1)',
      coords: [40.4156, -3.7074],
      blurb: 'Iconic 17th-century arcaded square. Statue of Felipe III; café terraces under the colonnade.',
    },
    {
      id: 'puerta-sol',
      name: 'Puerta del Sol',
      category: 'plaza', icon: '🏛️',
      address: 'Puerta del Sol, 28013',
      hours: 'Always open',
      cost: 'Free',
      duration: '20-30 min',
      metro: 'Sol (L1/L2/L3)',
      coords: [40.4168, -3.7038],
      blurb: 'Madrid’s symbolic centre. Km Zero plaque, Tio Pepe sign, Bear & Strawberry Tree statue.',
    },
    {
      id: 'prado',
      name: 'Museo Nacional del Prado',
      category: 'museum', icon: '🎨',
      address: 'C. de Ruiz de Alarcón 23, 28014',
      hours: 'Mon-Sat 10:00-20:00; Sun 10:00-19:00. Closed 1 May.',
      cost: '€15 (free last 2 h daily)',
      duration: '2.5 h',
      metro: 'Banco de España (L2), Atocha (L1)',
      coords: [40.4138, -3.6921],
      blurb: 'Spain’s flagship art museum. Velázquez, Goya, El Greco, Bosch, Titian.',
      link: 'https://www.museodelprado.es/en/visit/opening-times-and-prices',
    },
    {
      id: 'reina-sofia',
      name: 'Museo Reina Sofía',
      category: 'museum', icon: '🎨',
      address: 'C. de Sta. Isabel 52, 28012',
      hours: 'Mon, Wed-Sat 10:00-21:00; Sun 10:00-14:30. Closed Tue & 1 May.',
      cost: '€12 (free Mon & Wed-Sat 19:00-21:00; Sun 12:30-14:30)',
      duration: '2 h',
      metro: 'Atocha (L1), Estación del Arte (L1)',
      coords: [40.4080, -3.6943],
      blurb: 'Spain’s national modern-art museum. Picasso’s Guernica is the centrepiece; also Dalí, Miró.',
      link: 'https://www.museoreinasofia.es/en/visit/opening-times/',
    },
    {
      id: 'templo-debod',
      name: 'Templo de Debod',
      category: 'temple', icon: '🏺',
      address: 'C. de Ferraz 1, 28008',
      hours: 'Outdoor 24/7; interior Tue-Sun 10:00-19:00',
      cost: 'Free',
      duration: '45 min - 1 h',
      metro: 'Plaza de España (L3/L10), Ventura Rodríguez (L3)',
      coords: [40.4239, -3.7174],
      blurb: 'Real Egyptian temple gifted to Spain in 1968 — Madrid’s best free sunset viewpoint.',
    },
    {
      id: 'mercado-san-miguel',
      name: 'Mercado de San Miguel',
      category: 'market', icon: '🛒',
      address: 'Pl. de San Miguel s/n, 28005',
      hours: 'Daily 10:00-24:00',
      cost: 'Free entry; tapas €3-€8',
      duration: '1-1.5 h',
      metro: 'Sol (L1/L2/L3), Tirso de Molina (L1)',
      coords: [40.4154, -3.7088],
      blurb: 'Iconic glass-and-iron food market beside Plaza Mayor. Touristy but lovely; go off-peak (12-13).',
    },
    {
      id: 'rastro',
      name: 'El Rastro Sunday Market',
      category: 'market', icon: '🛒',
      address: 'Calle Ribera de Curtidores, 28005',
      hours: 'Sundays & holidays 09:00-15:00',
      cost: 'Free',
      duration: '1.5-2 h',
      metro: 'La Latina (L5), Tirso de Molina (L1)',
      coords: [40.4096, -3.7080],
      blurb: 'Madrid’s classic open-air flea market — antiques, leather, vintage clothes, vinyl.',
    },
    {
      id: 'almudena',
      name: 'Almudena Cathedral',
      category: 'church', icon: '⛪',
      address: 'C. de Bailén 10, 28013',
      hours: 'Daily 10:00-20:30',
      cost: 'Free (donation €1); Museum + Dome €7',
      duration: '30-45 min',
      metro: 'Ópera (L2/L5/R)',
      coords: [40.4157, -3.7142],
      blurb: 'Modern cathedral facing the Royal Palace. Crypt and dome accessible separately.',
    },
  ],

  /* Rooftop bars — sorted by entry fee, low → high */
  rooftops: [
    {
      id: 'picalagartos',
      name: 'Picalagartos Sky Bar',
      category: 'rooftop', icon: '🍸',
      address: 'C. de Alcalá 4, 28014 (NH Collection Madrid Gran Vía, 8th-9th floor)',
      coords: [40.4187, -3.7000],
      hours: 'Daily ~13:00-01:30',
      cost: 'No entry fee with order; reservation recommended',
      bestTime: 'Sunset / golden hour',
      blurb: 'Free walk-in for the bar standing area; book a table for golden hour. Views over Gran Vía.',
      link: 'https://www.nh-collection.com/hotel/nh-collection-madrid-gran-via',
    },
    {
      id: 'the-hat',
      name: 'The Hat Rooftop',
      category: 'rooftop', icon: '🍸',
      address: 'C. Imperial 9, 28012 (behind Plaza Mayor)',
      coords: [40.4140, -3.7088],
      hours: 'Daily ~13:00-24:00',
      cost: 'No entry fee, no minimum',
      bestTime: 'Late afternoon / sunset',
      blurb: 'Relaxed hostel rooftop with no cover and no reservations needed. Pure walk-in.',
      link: 'https://www.thehatmadrid.com/the-rooftop',
    },
    {
      id: 'ginkgo',
      name: 'Ginkgo Sky Bar',
      category: 'rooftop', icon: '🍸',
      address: 'Pl. de España 5, 28008 (VP Plaza España Design, 12th fl.)',
      coords: [40.4234, -3.7126],
      hours: 'Daily 12:30-01:30',
      cost: '€3 weekday / €6 weekend (waived with reservation)',
      bestTime: 'Sunset for Royal Palace silhouette',
      blurb: 'Polished design hotel rooftop overlooking Plaza de España and the Royal Palace.',
      link: 'https://www.vphoteles.com/en/madrid/sky-bar',
    },
    {
      id: 'azotea-bellas-artes',
      name: 'Azotea del Círculo de Bellas Artes',
      category: 'rooftop', icon: '🍸',
      address: 'C. de Alcalá 42, 28014',
      coords: [40.4193, -3.6960],
      hours: 'Daily 12:00-02:00',
      cost: '€5-€5.50 entrance (includes art-centre access)',
      bestTime: 'Arrive 30 min before sunset',
      blurb: 'The classic Madrid sunset shot — Metrópolis dome, Gran Vía, Cibeles all in frame.',
      link: 'https://circulobellasartes.com/azotea/',
    },
    {
      id: '360-rooftop',
      name: '360° Rooftop Bar',
      category: 'rooftop', icon: '🍸',
      address: 'Pl. de España 8, 28008 (Riu Plaza España, 27th fl.)',
      coords: [40.4233, -3.7117],
      hours: 'Daily 11:00-24:00',
      cost: '€5 (day) / €10 (eve & weekends), not redeemable',
      bestTime: 'Sunset / night',
      blurb: 'Highest 360° city panorama in Madrid. Long queues at peak; arrive early.',
      link: 'https://www.riu360rooftopbar.com/en/',
    },
  ],

  /* Restaurants curated to the brief */
  restaurants: [
    {
      name: 'La Castela',
      address: 'C. del Doctor Castelo 22, 28009 (Retiro)',
      coords: [40.4183, -3.6741],
      cuisine: 'Traditional Madrileño tapas',
      pricePerPerson: '€20-€25',
      rating: 4.5, reviews: '2,500+',
      atmosphere: 'Buzzy, locals-heavy, white-tiled bar; warm',
      bestDish: 'Croquetas de jamón + tortilla de patata',
      assignedDay: 'Day 1 dinner',
    },
    {
      name: 'La Barraca',
      address: 'C. de la Reina 29, 28004 (Gran Vía)',
      coords: [40.4194, -3.6987],
      cuisine: 'Valencian / paella since 1935',
      pricePerPerson: '€28-€35',
      rating: 4.4, reviews: '1,200+',
      atmosphere: 'Old-world Valencian decor, intimate, unhurried',
      bestDish: 'Paella valenciana (chicken & rabbit) or arroz negro',
      assignedDay: 'Day 2 dinner',
    },
    {
      name: 'Mercado de San Miguel',
      address: 'Pl. de San Miguel s/n, 28005',
      coords: [40.4154, -3.7088],
      cuisine: 'Tapas grazing',
      pricePerPerson: '€15-€25',
      rating: 4.3, reviews: '140,000+',
      atmosphere: 'Lively glass market; crowded but iconic — go off-peak (12-13)',
      bestDish: 'Jamón ibérico cones, oysters, vermouth',
      assignedDay: 'Day 2 lunch',
    },
    {
      name: 'Casa Mortero',
      address: 'C. de Zorrilla 9, 28014 (Las Cortes)',
      coords: [40.4159, -3.6960],
      cuisine: 'Modern traditional Spanish (Michelin-Bib)',
      pricePerPerson: '€35-€45',
      rating: 4.7, reviews: '1,700+',
      atmosphere: 'Minimalist-industrial; calm; one of Madrid’s best price-to-quality',
      bestDish: 'Torreznos, oxtail, grilled cod',
      assignedDay: 'Day 3 lunch (splurge)',
    },
    {
      name: 'Casa Benigna',
      address: 'C. Benigno Soto 9, 28002 (Chamartín)',
      coords: [40.4493, -3.6770],
      cuisine: 'Mediterranean / paella',
      pricePerPerson: '€30-€40',
      rating: 4.6, reviews: '1,000+',
      atmosphere: 'Cosy living-room feel; chef’s-table vibe; reservations essential',
      bestDish: 'Paella de pluma ibérica',
      assignedDay: 'Day 3 dinner',
      note: 'Walking distance from hotel.',
    },
    {
      name: 'Bodega de la Ardosa',
      address: 'C. de Colón 13, 28004 (Malasaña)',
      coords: [40.4244, -3.7027],
      cuisine: 'Classic 1892 tapas tavern',
      pricePerPerson: '€15-€25',
      rating: 4.5, reviews: '5,500+',
      atmosphere: 'Old tile-and-barrel bodega; standing & high tables',
      bestDish: 'Salmorejo, award-winning tortilla, vermouth on tap',
      assignedDay: 'Day 4 late dinner',
    },
    {
      name: 'Casa Dani',
      address: 'C. de Ayala 28, 28001 (Mercado de la Paz, Salamanca)',
      coords: [40.4254, -3.6822],
      cuisine: 'Traditional / menú del día',
      pricePerPerson: '€15-€20',
      rating: 4.5, reviews: '3,500+',
      atmosphere: 'Bustling market stall + dining room; National Tortilla Champion',
      bestDish: 'Tortilla de patata con cebolla, callos',
      assignedDay: 'Day 5 dinner',
    },
    {
      name: 'Taberna Tempranillo',
      address: 'C. Cava Baja 38, 28005 (La Latina)',
      coords: [40.4123, -3.7095],
      cuisine: 'Tapas + Spanish wine',
      pricePerPerson: '€20-€28',
      rating: 4.4, reviews: '2,000+',
      atmosphere: 'Atmospheric Cava Baja tavern; massive wine list',
      bestDish: 'Pulpo a la gallega, queso board',
      assignedDay: 'Day 6 brunch / late lunch',
    },
  ],

  /* Day trips */
  dayTrips: [
    {
      name: 'Toledo',
      status: 'mandatory',
      assignedDay: 'Sat 2 May',
      coords: [39.8628, -4.0273],
      highlights: [
        'Toledo Cathedral (Catedral Primada) — Gothic masterpiece',
        'El Greco’s Burial of Count Orgaz at Iglesia de Santo Tomé',
        'Sinagoga del Tránsito / Sephardic Museum',
        'Alcázar of Toledo & Army Museum',
        'Mirador del Valle for skyline panorama; marzipan tasting',
      ],
      transport: 'Renfe Avant Madrid Atocha → Toledo. €13.90 each way; 33 min. ~14 services/day weekdays, ~10 on weekends.',
      cost: '~€70-€90 pp (train + monuments + lunch)',
      duration: 'Full day (8-10 h) recommended',
      weather: 'Cobblestone, hilly, mostly outdoor — pack a light rain jacket.',
    },
    {
      name: 'Valencia',
      status: 'mandatory',
      assignedDay: 'Fri 1 May',
      coords: [39.4699, -0.3763],
      highlights: [
        'Valencia Cathedral & Miguelete Tower (Holy Grail)',
        'Mercado Central; Lonja de la Seda (UNESCO silk exchange)',
        'Ciudad de las Artes y las Ciencias (Calatrava architecture)',
        'Oceanogràfic or Hemisfèric IMAX',
        'Malvarrosa Beach + paella in its birthplace',
      ],
      transport: 'AVE / Iryo / Avlo / Ouigo to Valencia Joaquín Sorolla. 1h 54 min direct; ~18 trains/day. Avlo from €29.',
      cost: '€115-€180 pp (train + entries + lunch)',
      duration: 'Full day (~9 h on the ground)',
      weather: 'Reliably warmer than Madrid (22-26 °C); excellent rain backup.',
      sameDayVerdict: 'Same-day return is the right fit for this 5-day Madrid-base trip.',
    },
    {
      name: 'Segovia',
      status: 'optional-recommend',
      assignedDay: 'Skip — save for return trip',
      coords: [40.9501, -4.1183],
      highlights: ['Roman Aqueduct', 'Alcázar (Cinderella inspiration)', 'Cathedral'],
      transport: 'AVE 27 min from Chamartín to Segovia-Guiomar; bus 11 to old town.',
      cost: '~€26 train',
      duration: 'Half-day or full-day',
      verdict: 'Strongly recommended if you had a 6th day. Could replace Toledo, but Toledo is closer & richer culturally.',
    },
    {
      name: 'El Escorial',
      status: 'optional-skip',
      assignedDay: 'Skip',
      coords: [40.5896, -4.1498],
      highlights: ['UNESCO Royal Monastery of Philip II'],
      transport: 'Cercanías C-3 from Atocha or Chamartín, ~1 h. Covered by Tourist Pass Zone T.',
      cost: '~€8.40 round-trip with Zone T pass',
      duration: 'Half-day',
      verdict: 'Doesn’t fit a packed 5-day Madrid-base unless you skip the Royal Palace.',
    },
    {
      name: 'Ávila',
      status: 'optional-skip',
      assignedDay: 'Skip',
      coords: [40.6566, -4.6815],
      highlights: ['Walled city walk', 'Cathedral'],
      transport: '~1.5 h each way',
      cost: 'Variable',
      duration: 'Full day',
      verdict: 'Beautiful but too much travel for 5 days. Better paired with Segovia.',
    },
    {
      name: 'Alcalá de Henares',
      status: 'optional-recommend',
      assignedDay: 'Skip in this packed itinerary',
      coords: [40.4818, -3.3644],
      highlights: ['Cervantes’ birthplace', 'University town'],
      transport: 'Cercanías C-2 / C-7 from Chamartín ~40 min; covered by Zone T pass.',
      cost: '~€7 with Zone T pass',
      duration: 'Half-day',
      verdict: 'Possible half-day option if a Madrid day frees up.',
    },
  ],

  /* Practical info cards */
  practical: [
    {
      title: 'Public holidays',
      body: [
        '<strong>Fri 1 May</strong> — Labour Day (national). Royal Palace, Prado, Reina Sofía, Thyssen <strong>all closed</strong>. Metro on Sunday/holiday schedule. AVE/Avant intercity normal. Many shops shut. Plan: Valencia day trip.',
        '<strong>Sat 2 May</strong> — Día de la Comunidad de Madrid (regional). Most attractions open but heavy crowds (long weekend). Plan: Toledo (outside region, unaffected).',
      ],
    },
    {
      title: 'Transport tips',
      list: [
        'Avoid 08:00-09:30 and 18:00-20:00 Mon-Fri on Metro & Cercanías.',
        '<strong>Tarjeta Multi card</strong> (€2.50, rechargeable) required for any pass or single ticket. Tourist Pass is personal/non-transferable.',
        'Night buses (<em>Búhos</em>) run from Plaza de Cibeles after Metro closes; covered by Tourist Pass.',
        'AVE / Avlo / Iryo / Ouigo are <strong>not</strong> covered by any travel pass — book separately.',
      ],
    },
    {
      title: 'City Card analysis (3 pax, 5 days)',
      body: [
        '<strong>Zone A 5-day Tourist Travel Pass</strong>: €32.50 × 3 = €97.50. Includes airport supplement. Beats pay-as-you-go (~€42 pp) by ~€30 total.',
        '<strong>Zone T pass</strong> (€49 × 3) only worth it if adding El Escorial / Aranjuez. Does <em>not</em> cover Avant to Toledo or AVE to Valencia.',
        'Madrid <strong>City Card</strong>: discounts target attractions you’re not visiting; savings minimal vs. Zone A pass.',
      ],
      recommendation: '✅ Buy 3 × Zone A 5-day Tourist Travel Passes at the airport on arrival — €97.50 group total.',
    },
    {
      title: 'Packing — late April / early May',
      body: ['Highs 18-22 °C, lows 9-12 °C, ~21% rain probability per day, ~10 °C day-night swing.'],
      list: [
        'Comfortable walking shoes (Toledo cobblestones).',
        'Layers: t-shirt + light sweater + packable jacket.',
        'Light rainproof jacket / compact umbrella.',
        'Smart-casual outfit for rooftops & dinners (no shorts/flip-flops).',
        'Daypack, sunglasses, SPF 30+, EU power adapter (Type C/F).',
        'Photo ID/passport required at Royal Palace, Bernabéu, AVE security.',
      ],
    },
    {
      title: 'Pre-book ahead of time',
      list: [
        'Royal Palace, Bernabéu Tour, Prado, Reina Sofía — timed entry.',
        'AVE/Iryo to Valencia (book 3+ weeks ahead for &lt;€60 fares).',
        'Avant to Toledo (Saturday services drop to ~10/day).',
        'Casa Mortero, La Barraca, Casa Benigna — reserve 48 h ahead.',
      ],
    },
    {
      title: 'Money & misc',
      list: [
        'Carry ~€40 cash each — most places take cards but small tapas bars and El Rastro vendors prefer cash.',
        'Madrid tap water is excellent — refill at park fountains.',
        'Tipping: round up the bill or 5-10% at sit-down dinners; not expected at tapas bars.',
      ],
    },
  ],
};

window.TRIP = TRIP;
